###
GET http://localhost:8080/v1/greet/randomName
###
GET {{baseURL}}/greet/Jan
###
POST {{baseURL}}/greet/Jan

### post course
POST {{baseURL}}/courses
Content-Type: application/json

{
  "id": null,
  "name": "BECOME A FROG IN DAYS",
  "category" : "METAMORPHISM"
}


#### get all
GET {{baseURL}}/courses
Content-Type: application/json