###
GET http://localhost:8080/v1/greet/randomName
###
GET {{baseURL}}/greet/Jan
###
POST {{baseURL}}/greet/Jan

### post course
POST {{baseURL}}/courses
Content-Type: application/json

{
  "id": null,
  "name": "BECOME A FROG IN DAYS",
  "category" : "METAMORPHISM"
}


#### get all
GET {{baseURL}}/courses
Content-Type: application/json

### put, before you do it, just post line 9
PUT  {{baseURL}}/courses/1
Content-Type: application/json

{
  "id": 1,
  "name": "BECOME A WIZARD IN DAYS",
  "category" : "METAMORPHISM"
}

### delete // this delete sucks, cuz @responseBody, we desire DELET baseUIR/id not to pass the complete obj here right?
DELETE {{baseURL}}/courses
Content-Type: application/json

{
  "id": 1,
  "name": "BECOME A FROG IN DAYS",
  "category": "METAMORPHISM"
}